name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code (run actions/checkout@v3)
        uses: actions/checkout@v3

      - name: Setup Node.js (run actions/setup-node@v3)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Lint
        run: npm run eslint -- --fix

      - name: Build
        run: npm run build
#
#      - name: Run Playwright E2E Tests
#        run: npm run test:e2e
#
#      - name: Upload Playwright Test Report
#        if: failure()
#        uses: actions/upload-artifact@v3
#        with:
#          name: playwright-report
#          path: playwright-report/
